-- Seed 6 articole — generat cu gen_articole.py
BEGIN;

INSERT INTO ec_articole (id, slug, status, locale, title, excerpt, category, content, reading_time, published_at, created_at, updated_at, og_image)
VALUES
('01KRTQ00000000000000000A01', 'puterea-rugaciunii-in-vindecare',
 'published', 'ro',
 'Puterea rugăciunii în vindecare — ce spune știința și credința',
 'Rugăciunea nu este doar o practică religioasă — studii medicale recente arată că ea influențează pozitiv sănătatea trupului și a minții. Descoperă ce spun cercetătorii și ce învață Biserica Ortodoxă despre tămăduire.',
 'Vindecare spirituală',
 '[{"_type": "block", "_key": "blk1", "style": "normal", "children": [{"_type": "span", "_key": "spn1", "text": "De-a lungul veacurilor, creștinii ortodocși au știut că rugăciunea vindecă. Dar abia în ultimele decenii, medicina modernă a început să cerceteze serios această legătură dintre credință și sănătate, descoperind rezultate surprinzătoare.", "marks": []}]}, {"_type": "block", "_key": "blk2", "style": "normal", "children": [{"_type": "span", "_key": "spn2", "text": "Studii realizate la Universitatea Harvard și la Duke University au arătat că persoanele care se roagă regulat au un sistem imunitar mai puternic, se recuperează mai rapid după operații și trăiesc, în medie, cu 7-14 ani mai mult decât cei care nu practică nicio formă de spiritualitate.", "marks": []}]}, {"_type": "block", "_key": "blk3", "style": "normal", "children": [{"_type": "span", "_key": "spn3", "text": "Din perspectiva ortodoxă, rugăciunea nu este o tehnica psihologică, ci o întâlnire reală cu Dumnezeu, Izvorul vieții și al sănătății. Sfântul Ioan Gură de Aur spunea: rugăciunea este rădăcina, izvorul și mama tuturor bunătăților.", "marks": []}]}, {"_type": "block", "_key": "blk4", "style": "normal", "children": [{"_type": "span", "_key": "spn4", "text": "Sfântul Luca al Crimeei, el însuși chirurg de renume, mărturisea că în operațiile dificile simțea o forță care îi ghida mâna dincolo de cunoștințele sale medicale. El nu vedea nicio contradicție între știință și credință — dimpotrivă, le considera complementare.", "marks": []}]}, {"_type": "block", "_key": "blk5", "style": "normal", "children": [{"_type": "span", "_key": "spn5", "text": "Practica rugăciunii zilnice — chiar și câteva minute dimineața și seara — creează o stabilitate emoțională care se reflectă direct în sănătatea fizică. Cortizolul scade, tensiunea arterială se normalizează, somnul se îmbunătățește.", "marks": []}]}, {"_type": "block", "_key": "blk6", "style": "normal", "children": [{"_type": "span", "_key": "spn6", "text": "Concluzia este simplă: rugăciunea face bine. Nu ca magie, nu ca auto-sugestie, ci ca o relație vie cu Cel care ne-a creat și care dorește vindecarea noastră — trupească și sufletească. Rugați-vă cu credință și lăsați-L pe Dumnezeu să lucreze.", "marks": []}]}]',
 6,
 '2026-03-01 10:00:00+00', '2026-03-01 10:00:00+00', '2026-03-01 10:00:00+00',
 ''),

('01KRTQ00000000000000000A02', 'cum-sa-te-rogi-pentru-un-bolnav',
 'published', 'ro',
 'Cum să te rogi pentru un om bolnav — ghid practic ortodox',
 'Când cineva drag este bolnav, nu știm uneori cum să ne rugăm și ce să cerem de la Dumnezeu. Acest ghid practic ortodox îți arată cum să faci rugăciunea de mijlocire mai eficientă și mai plină de credință.',
 'Ghid spiritual',
 '[{"_type": "block", "_key": "blk1", "style": "normal", "children": [{"_type": "span", "_key": "spn1", "text": "Unul dintre cele mai dureroase momente din viață este atunci când un om drag zace bolnav și nu putem face nimic. Medicina are limitele ei. Dar rugăciunea nu are limite — ea ajunge acolo unde medicii nu pot.", "marks": []}]}, {"_type": "block", "_key": "blk2", "style": "normal", "children": [{"_type": "span", "_key": "spn2", "text": "Prima regulă a rugăciunii de mijlocire este: roagă-te cu credință, nu cu îndoială. Nu înseamnă că trebuie să fii sigur de rezultat — înseamnă să crezi că Dumnezeu te aude și că Îi pasă. Sfântul Iacov spune limpede: rugăciunea cu credință va vindeca pe cel bolnav.", "marks": []}]}, {"_type": "block", "_key": "blk3", "style": "normal", "children": [{"_type": "span", "_key": "spn3", "text": "A doua regulă: roagă-te regulat, nu doar o dată. Rugăciunea de mijlocire este un act de perseverență. Hristos însuși a spus pilda cu văduvă stăruitoare pentru a ne arăta că Dumnezeu răspunde la rugăciunile insistente.", "marks": []}]}, {"_type": "block", "_key": "blk4", "style": "normal", "children": [{"_type": "span", "_key": "spn4", "text": "A treia regulă: combină rugăciunea cu postul. Tradiția ortodoxă leagă strâns postul de rugăciune mai ales atunci când cerem ceva important. Chiar și un post parțial — renunțarea la ceva anume — însoțind rugăciunea sporește puterea ei.", "marks": []}]}, {"_type": "block", "_key": "blk5", "style": "normal", "children": [{"_type": "span", "_key": "spn5", "text": "A patra regulă: lasă rezultatul lui Dumnezeu. Aceasta este cea mai grea parte. Rugăciunea adevărată nu dictează lui Dumnezeu ce să facă — Îi prezintă nevoile și se încrede în înțelepciunea Sa. Uneori Dumnezeu vindecă imediat; alteori îngăduie suferința ca pe o cale spre sfințenie.", "marks": []}]}, {"_type": "block", "_key": "blk6", "style": "normal", "children": [{"_type": "span", "_key": "spn6", "text": "Rugați Sfântul Pantelimon, Sfântul Nectarie și Sfânta Parascheva să mijlocească pentru bolnavul vostru drag. Lor le-a dat Dumnezeu un dar special al tămăduirii, iar rugăciunile lor ajung direct la Tronul Celui Atotputernic.", "marks": []}]}]',
 5,
 '2026-03-15 10:00:00+00', '2026-03-15 10:00:00+00', '2026-03-15 10:00:00+00',
 ''),

('01KRTQ00000000000000000A03', 'psalmii-in-viata-crestinului-ortodox',
 'published', 'ro',
 'Psalmii în viața creștinului ortodox — comoara uitată a rugăciunii',
 'Cele 150 de psalmi ale lui David sunt cea mai veche și mai bogată colecție de rugăciuni din istoria omenirii. Descoperă cum să introduci psalmii în rugăciunea ta zilnică și ce beneficii aduc sufletului tău.',
 'Spiritualitate',
 '[{"_type": "block", "_key": "blk1", "style": "normal", "children": [{"_type": "span", "_key": "spn1", "text": "Cartea Psalmilor este inima Bibliei. Timp de trei mii de ani, evreii și creștinii au cântat și au rostit aceste texte în rugăciunile lor de zi și de noapte, în bucurie și în suferință, la naștere și la moarte.", "marks": []}]}, {"_type": "block", "_key": "blk2", "style": "normal", "children": [{"_type": "span", "_key": "spn2", "text": "Psalmii exprimă tot spectrul emoțiilor omenești: bucurie, tristețe, frică, nădejde, mânie, recunoștință, disperare și exultare. Nu există stare sufletească pe care un psalm să n-o fi exprimat deja, cu cuvinte mai bune decât am putea găsi noi.", "marks": []}]}, {"_type": "block", "_key": "blk3", "style": "normal", "children": [{"_type": "span", "_key": "spn3", "text": "Sfântul Atanasie cel Mare scria: psalmii sunt o oglindă a sufletului. Cel care îi citește cu atenție se vede pe sine, cunoaște mișcările inimii sale și află cuvintele potrivite pentru orice stare.", "marks": []}]}, {"_type": "block", "_key": "blk4", "style": "normal", "children": [{"_type": "span", "_key": "spn4", "text": "În tradiția ortodoxă, Psaltirea se citea integral în fiecare săptămână în mănăstiri și în fiecare două săptămâni de creștinii mai râvnitori. Astăzi, putem începe mai simplu: câte un psalm pe zi, dimineața sau seara.", "marks": []}]}, {"_type": "block", "_key": "blk5", "style": "normal", "children": [{"_type": "span", "_key": "spn5", "text": "Psalmul 50 este psalmul pocăinței — ideal pentru dimineață, ca o curățire a sufletului. Psalmul 90 este psalmul apărării — recomandat seara, pentru paza nopții. Psalmul 22 este psalmul nădejdii — de citit în orice moment de frică sau îndoială.", "marks": []}]}, {"_type": "block", "_key": "blk6", "style": "normal", "children": [{"_type": "span", "_key": "spn6", "text": "Nu citiți psalmii în grabă, ca pe o obligație. Citiți-i încet, savurând fiecare cuvânt, oprindu-vă la versetele care vă ating inima. Rugăciunea psalmilor nu este performanță — este conversație vie cu Dumnezeu.", "marks": []}]}]',
 7,
 '2026-03-28 10:00:00+00', '2026-03-28 10:00:00+00', '2026-03-28 10:00:00+00',
 ''),

('01KRTQ00000000000000000A04', 'sfantul-pantelimon-viata-si-minuni',
 'published', 'ro',
 'Sfântul Pantelimon — viața, minunile și cum să-i cerem ajutorul',
 'Sfântul Mare Mucenic și Tămăduitor Pantelimon este cel mai iubit sfânt al bolnavilor în lumea ortodoxă. Descoperă viața sa fascinantă, minunile atribuite mijlocirii sale și cum să te rogi lui cu credință.',
 'Sfinți',
 '[{"_type": "block", "_key": "blk1", "style": "normal", "children": [{"_type": "span", "_key": "spn1", "text": "Sfântul Pantelimon trăiește în inimile a milioane de creștini ortodocși din întreaga lume ca cel mai mare tămăduitor dintre sfinți. Prăznuit pe 27 iulie, el este invocat zilnic de bolnavi, de medici și de familiile celor suferinzi.", "marks": []}]}, {"_type": "block", "_key": "blk2", "style": "normal", "children": [{"_type": "span", "_key": "spn2", "text": "Povestea vieții sale este una dintre cele mai fascinante din hagiografia creștină. Fiu al unui senator păgân din Nicomidia, Pantelimon a primit o educație aleasă și a studiat medicina sub îndrumarea unui medic de curte. Era destinat unei cariere strălucite.", "marks": []}]}, {"_type": "block", "_key": "blk3", "style": "normal", "children": [{"_type": "span", "_key": "spn3", "text": "Convertirea sa la creștinism a venit printr-o întâlnire providențială cu preotul Ermolae, care l-a catehizat în credința creștină. Semnul care i-a pecetluit credința a fost vindecarea miraculoasă a unui copil orbit de o viperă — vindecare pe care Pantelimon a săvârșit-o invocând numele lui Hristos.", "marks": []}]}, {"_type": "block", "_key": "blk4", "style": "normal", "children": [{"_type": "span", "_key": "spn4", "text": "De atunci, viitorul sfânt a început să trateze bolnavii fără plată, mai ales pe cei săraci pe care doctorii plătiți nu-i îngrijeau. Faima sa a crescut rapid, atrăgând invidia altor medici care l-au denunțat autorităților ca creștin.", "marks": []}]}, {"_type": "block", "_key": "blk5", "style": "normal", "children": [{"_type": "span", "_key": "spn5", "text": "Chinuit cu cruzime — ars cu torțe aprinse, aruncat în mare cu o piatră de gât, expus la fiare sălbatice — sfântul a ieșit nevătămat din toate, convertind mulți martori la credința creștină. A fost în cele din urmă decapitat, iar din trupul său a curs lapte în loc de sânge.", "marks": []}]}, {"_type": "block", "_key": "blk6", "style": "normal", "children": [{"_type": "span", "_key": "spn6", "text": "Moaștele sale se află astăzi la Mănăstirea Sfântul Pantelimon din Muntele Athos, Grecia, unde pelerini din toată lumea vin să se roage. Rugăciunea lui este invocată mai ales pentru boli grave, operații și vindecări pe care medicina le consideră imposibile.", "marks": []}]}]',
 8,
 '2026-04-10 10:00:00+00', '2026-04-10 10:00:00+00', '2026-04-10 10:00:00+00',
 ''),

('01KRTQ00000000000000000A05', 'rugaciunea-de-dimineata-cum-si-de-ce',
 'published', 'ro',
 'Rugăciunea de dimineață — cum și de ce să începi ziua cu Dumnezeu',
 'Dimineața dă tonul întregii zile. Descoperă de ce rugăciunea de dimineață este cea mai importantă rugăciune a zilei, cum să o faci corect și ce schimbări vei observa în viața ta după 30 de zile de practică.',
 'Viață duhovnicească',
 '[{"_type": "block", "_key": "blk1", "style": "normal", "children": [{"_type": "span", "_key": "spn1", "text": "Există o lege simplă a vieții duhovnicești: cum îți începi ziua, așa o trăiești. Dacă prima ta acțiune dimineața este să verifici telefonul, ziua va fi dominată de zgomotul lumii. Dacă prima ta acțiune este rugăciunea, ziua va fi ancorată în Dumnezeu.", "marks": []}]}, {"_type": "block", "_key": "blk2", "style": "normal", "children": [{"_type": "span", "_key": "spn2", "text": "Sfinții Părinți au acordat o importanță deosebită rugăciunii de dimineață. Sfântul Ioan Gură de Aur spunea că cel care nu se roagă dimineața lasă casa fără strajă — orice duh rău poate intra. Rugăciunea de dimineață sfințește ziua și o pune sub protecția lui Dumnezeu.", "marks": []}]}, {"_type": "block", "_key": "blk3", "style": "normal", "children": [{"_type": "span", "_key": "spn3", "text": "Cum se face rugăciunea de dimineață în tradiția ortodoxă? Tradiționalmente, ea include: Rugăciunea Sfântului Macarie, Rugăciunea Sfântului Vasile cel Mare, câțiva psalmi și Crezul. Dar pentru un începător, e suficient să înceapă cu Tatăl Nostru și câteva cuvinte din inimă.", "marks": []}]}, {"_type": "block", "_key": "blk4", "style": "normal", "children": [{"_type": "span", "_key": "spn4", "text": "Locul rugăciunii contează. Amenajați un colț de rugăciune în casă — cu o icoană și o candelă sau lumânare. Acest spațiu sfânt va deveni un reper vizual care vă cheamă la rugăciune și creează o atmosferă potrivită.", "marks": []}]}, {"_type": "block", "_key": "blk5", "style": "normal", "children": [{"_type": "span", "_key": "spn5", "text": "Durata rugăciunii de dimineață pentru un laic poate fi de 5-15 minute. Nu cantitatea contează, ci calitatea și regularitatea. Mai bine 5 minute zilnic decât o oră o dată pe săptămână.", "marks": []}]}, {"_type": "block", "_key": "blk6", "style": "normal", "children": [{"_type": "span", "_key": "spn6", "text": "Provocare practică: timp de 30 de zile, rugați-vă dimineața înainte de a verifica telefonul sau de a face orice altceva. La final, evaluați ce s-a schimbat în starea voastră sufletească, în relațiile cu ceilalți și în modul în care faceți față greutăților zilei.", "marks": []}]}]',
 5,
 '2026-04-22 10:00:00+00', '2026-04-22 10:00:00+00', '2026-04-22 10:00:00+00',
 ''),

('01KRTQ00000000000000000A06', 'credinta-si-medicina-complement-nu-conflict',
 'published', 'ro',
 'Credință și medicină — complement, nu conflict',
 'Un subiect delicat dar important: relația dintre rugăciune și tratamentul medical. Ce spune Biserica Ortodoxă? Trebuie să alegem între medic și rugăciune? Răspunsul surprinzător al tradiției creștine.',
 'Sănătate și credință',
 '[{"_type": "block", "_key": "blk1", "style": "normal", "children": [{"_type": "span", "_key": "spn1", "text": "Unii creștini cred că a apela la medic înseamnă lipsă de credință. Alții cred că rugăciunea este o practică superstițioasă incompatibilă cu medicina modernă. Ambele extreme sunt greșite și dăunătoare.", "marks": []}]}, {"_type": "block", "_key": "blk2", "style": "normal", "children": [{"_type": "span", "_key": "spn2", "text": "Biserica Ortodoxă a avut dintotdeauna o atitudine echilibrată față de medicină. Sfântul Luca Evanghelistul era el însuși medic. Sfântul Luca al Crimeei era chirurg. Sfântul Cosma și Sfântul Damian practicau medicina. Medicina este văzută ca un dar al lui Dumnezeu pentru binele omului.", "marks": []}]}, {"_type": "block", "_key": "blk3", "style": "normal", "children": [{"_type": "span", "_key": "spn3", "text": "Sfântul Vasile cel Mare, întemeietorul primului spital din istoria omenirii, scria: nu este lipsă de credință să cauți ajutorul artei medicale. Medicina este un dar dumnezeiesc, dar nu îl uita pe Dătătorul darurilor.", "marks": []}]}, {"_type": "block", "_key": "blk4", "style": "normal", "children": [{"_type": "span", "_key": "spn4", "text": "Atitudinea corectă este să folosim ambele: medicina pentru vindecare trupească și rugăciunea pentru harul lui Dumnezeu care sfințește și potențează tratamentul. Nu sunt alternative — sunt complementare.", "marks": []}]}, {"_type": "block", "_key": "blk5", "style": "normal", "children": [{"_type": "span", "_key": "spn5", "text": "Practic: mergi la medic, urmează tratamentul prescris, ia medicamentele, fă investigațiile recomandate. Și în același timp: roagă-te, cere ungerea cu Sfântul Maslu, invocă sfinții tămăduitori, participă la Sfânta Liturghie.", "marks": []}]}, {"_type": "block", "_key": "blk6", "style": "normal", "children": [{"_type": "span", "_key": "spn6", "text": "Există mărturii documentate de vindecări care depășesc explicațiile medicale — minuni săvârșite prin mijlocirea sfinților. Dar aceste minuni nu neagă medicina; ele o completează acolo unde medicina ajunge la limitele ei. Dumnezeu lucrează și prin medici, și dincolo de medici.", "marks": []}]}]',
 6,
 '2026-05-01 10:00:00+00', '2026-05-01 10:00:00+00', '2026-05-01 10:00:00+00',
 '');

COMMIT;
